garis='-'*35
print(garis)
print("Tugas 1 SISOP Kelas-B")
print(garis)
print("Nama : Alya Mirza Safira")
print("NPM : 21083010039")
print(garis)
print("notes")
print(garis)
print("Halloo Dunia!")
print("Ini adalah script python pertamaku di Linux")
